apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
spec:
  selector:
    app: hackathon-poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-poi
  template:
    metadata:
      labels:
        app: hackathon-poi
    spec:
      containers:
      - name: poi
        image: registryzdv5829.azurecr.io/tripinsights/poi:1.0
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: SQL_SERVER
            value: sqlserverzdv5829.database.windows.net
        ports:
        - containerPort: 80