apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
spec:
  selector:
    app: hackathon-trips
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-trips
  template:
    metadata:
      labels:
        app: hackathon-trips
    spec:
      containers:
      - name: trips
        image: registryzdv5829.azurecr.io/tripinsights/trips:1.0
        env:
        - name: CONFIG_FILES_PATH
          value: /mnt/secrets-store        
        - name: OPENAPI_DOCS_URI
          value: "http://localhost"
        # - name: SQL_PASSWORD
        #   value: /mnt/secret-store/SQL_PASSWORD
        # - name: SQL_USER
        #   value: /mnt/secret-store/SQL_USER
        # - name: SQL_SERVER
        #   value: /mnt/secret-store/SQL_SERVER
        # - name: SQL_DBNAME
        #   value: /mnt/secret-store/SQL_DBNAME                          
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"        