apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
spec:
  selector:
    app: hackathon-trips
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-trips
  template:
    metadata:
      labels:
        app: hackathon-trips
    spec:
      containers:
      - name: trips
        image: registryzdv5829.azurecr.io/tripinsights/trips:1.0
        env:
          - name: OPENAPI_DOCS_URI
            value: "http://localhost"
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: SQL_PASSWORD
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: SQL_USER
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: SQL_DBNAME                           
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"        