apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
spec:
  selector:
    app: hackathon-trips
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-trips
  template:
    metadata:
      labels:
        app: hackathon-trips
    spec:
      containers:
      - name: trips
        image: registryzdv5829.azurecr.io/tripinsights/trips:1.0
        env:
          - name: DEBUG_LOGGING
            value: "true"
          - name: SQL_SERVER
            value: sqlserverzdv5829.database.windows.net
          - name: OPENAPI_DOCS_URI
            value: "http://localhost"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password                
        ports:
        - containerPort: 80