apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: hackathon-tripviewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-tripviewer
  template:
    metadata:
      labels:
        app: hackathon-tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryzdv5829.azurecr.io/tripinsights/tripviewer:1.0
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile-service.api.svc.cluster.local:80
          - name: TRIPS_API_ENDPOINT
            value: http://trips-service.api.svc.cluster.local:80
        ports:
        - containerPort: 80