apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  selector:
    app: hackathon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
      - name: trips
        image: registryzdv5829.azurecr.io/tripinsights/trips:1.0
        env:
          SQL_USER: sqladminqKl0163
          SQL_PASSWORD: yV7ap3Ht1
          SQL_SERVER: sqlserverqkl0163
        ports:
        - containerPort: 