apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  selector:
    app: hackathon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
      - name: trips
        image: registryzdv5829.azurecr.io/tripinsights/trips:1.0
        env:
          - name: SQL_USER
            value: sqladminzDv5829
          - name: SQL_PASSWORD
            value: Demopass20240127
          - name: SQL_SERVER
            value: sqlserverzdv5829.database.windows.net
          - name: OPENAPI_DOCS_URI
            value: "http://localhost"
        ports:
        - containerPort: 80