apiVersion: v1
kind: Service
metadata:
  name: userapi-service
  namespace: api
spec:
  selector:
    app: hackathon-user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-user-java
  template:
    metadata:
      labels:
        app: hackathon-user-java
    spec:
      containers:
      - name: userapi
        image: registryzdv5829.azurecr.io/tripinsights/userapi:1.0
        ports:
        - containerPort: 80
        env:        
        - name: SQL_PASSWORD
          value: /secrets/SQL_PASSWORD
        - name: SQL_USER
          value: /secrets/SQL_USER
        - name: SQL_SERVER
          value: /secrets/SQL_SERVER
        - name: SQL_DBNAME
          value: /secrets/SQL_DBNAME        
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"        