apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api
spec:
  selector:
    app: hackathon-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-user
  template:
    metadata:
      labels:
        app: hackathon-user
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: userprofile
        image: registryzdv5829.azurecr.io/tripinsights/userprofile:1.0
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault        
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_FILES_PATH
          value: /mnt/secrets-store
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"        