apiVersion: v1
kind: Service
metadata:
  name: userapi-service
  namespace: api
spec:
  selector:
    app: hackathon-user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-user-java
  template:
    metadata:
      labels:
        app: hackathon-user-java
    spec:
      containers:
      - name: userapi
        image: registryzdv5829.azurecr.io/tripinsights/userapi:1.0
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: SQL_SERVER
            value: sqlserverzdv5829.database.windows.net
        ports:
        - containerPort: 80