kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-user-full-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-user-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-user-full-access
subjects:
- kind: Group
  namespace: web
  name: 23e8ab22-719f-4062-bf81-4ca26282be64
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-dev-read-access-role
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-read-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-read-access-role
subjects:
- kind: Group
  namespace: web
  name: 23e8ab22-719f-4062-bf81-4ca26282be64